# Generated by Django 4.2.13 on 2026-06-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='kbentry',
            options={'ordering': ['category', 'id'], 'verbose_name': 'Knowledge Base Entry', 'verbose_name_plural': 'Knowledge Base Entries'},
        ),
        migrations.AlterModelOptions(
            name='querylog',
            options={'ordering': ['-queried_at'], 'verbose_name': 'Query Log', 'verbose_name_plural': 'Query Logs'},
        ),
        migrations.AlterField(
            model_name='querylog',
            name='results_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['company', 'queried_at'], name='api_querylo_company_ac5248_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['search_term'], name='api_querylo_search__3b90bd_idx'),
        ),
    ]
